# Generated by Django 4.0.3 on 2022-03-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('pickup', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=500)),
                ('location_link', models.URLField(max_length=500)),
            ],
        ),
    ]
